### ISSUE TITLE
[Question] Comparator for HighLevelNode::cost should be < ?

### ISSUE THREAD

**Issue by Shushman** [whoenig/libMultiRobotPlanning#12]
Beginner's question about this line: https://github.com/whoenig/libMultiRobotPlanning/blob/master/include/libMultiRobotPlanning/cbs.hpp#L189

If I understood the paper correctly, the high-level search is best-first according to lowest node cost; and I believe the `d_ary_heap` is a min-heap, so shouldn't the line be `return cost < n.cost` instead? What am I missing?

**Comment by whoenig** [comment]
Boost uses max heaps rather than min heaps, see https://www.boost.org/doc/libs/1_70_0/doc/html/heap/concepts.html.

**Comment by Shushman** [comment]
Whoops, my bad. Thanks!
