### ISSUE TITLE
Question about fmin in ECBS

### ISSUE THREAD

**Issue by Shushman** [whoenig/libMultiRobotPlanning#14]
Pardon me if this is extremely specific, but I really want to get to the bottom of one thing in ECBS. According to the original paper by Barer et al, in the subsection on *Enhanced CBS* just before *Experimental Results*, fmin(i) is the minimal f-value in the OPEN list used for the ith agent's low-level search. Certainly, that should be a lower bound on the optimal consistent cost-to-go.

My understanding is that fmin(i) should be the lowest f-value encountered during the entire low-level focal search for that agent, i.e. the lowest f-value among all of the focal heap entries that were expanded. 

According to this line, however (https://github.com/whoenig/libMultiRobotPlanning/blob/master/include/libMultiRobotPlanning/a_star_epsilon.hpp#L210), it seems that the `solution.fmin` looks at the lowest f-value _when the solution is expanded_. Is that not different from the lowest f-value seen throughout the search?

**Comment by whoenig** [comment]
I agree that lowest f-value seen through the search might be smaller than the current lowest f-value. However, the low-level search (as a best-first-search) already determined which f-values cannot be achieved in practice (the current f-value is always a lower bound on the solution cost). Thus, the value chosen in the code is also a lower bound on the cost.

I am not sure how the original authors of the ECBS code exactly implemented their estimate as I have not seen their code.

**Comment by Shushman** [comment]
Ah yes, the logic definitely makes sense - I just wanted to check that my understanding did as well. Thanks!
