### ISSUE TITLE
Need help working with cbs_ta and ecbs_ta

### ISSUE THREAD

**Issue by aditjha** [whoenig/libMultiRobotPlanning#19]
Hello! Thank you so much for your repo, very useful information. I was trying to visualize an **ecbs_ta** and **cbs_ta** example however I kept running into this:
`Traceback (most recent call last):
  File "visualize.py", line 162, in <module>
    animation = Animation(map, schedule)
  File "visualize.py", line 57, in __init__
    self.patches.append(Rectangle((d["goal"][0] - 0.25, d["goal"][1] - 0.25), 0.5, 0.5, facecolor=Colors[i%len(Colors)], edgecolor='black', alpha=0.5))
KeyError: 'goal'`

I was using the `mapfta_simple1_a1.yaml` example test file, and I know the key in this file is **potentialGoals**. So I am not sure how I can visualize my results when I am using either task allocation algorithm??

I would really appreciate the help, thank you in advance!

**Comment by whoenig** [comment]
This should be fixed in the latest version.

```
./cbs_ta -i ../test/mapfta_simple1_a1.yaml -o output.yaml
python3 ../example/visualize.py ../test/mapfta_simple1_a1.yaml output.yaml
```
Thanks for the report!
