### ISSUE TITLE
Undefined References from yaml-cpp During Build Process

### ISSUE THREAD

**Issue by JustinKottinger** [whoenig/libMultiRobotPlanning#23]
Hello, 

I am trying to build the demo's using the process outlined in the README on Ubuntu 18.04. The following is an outline of my process:

1. Install dependencies outlined in the repo 
`sudo apt-get install g++ cmake libboost-program-options-dev libyaml-cpp-dev clang-tidy clang-format python3-matplotlib graphviz doxygen`
2. `mkdir build`
`cd build`
`cmake ..`
`make`

CMAKE claims to find all required libraries. However, during the build process, I get an error while building the planners. I have attached the error message below. I would appreciate some guidance on how to resolve this error. Thank you in advance
![Screen Shot 2020-11-21 at 7 53 30 PM](https://user-images.githubusercontent.com/60479307/99892564-3ccdb300-2c33-11eb-832b-7600e589b70a.png)
!

**Comment by whoenig** [comment]
Hi,
This is very strange! Could you try running `make -k` and see which targets work and which ones fail? (The `-k` flag tells make to keep going even if there is an error.)

**Comment by JustinKottinger** [comment]
Thank you for getting back to me. 

The targets that worked:
- a_star
- assignment
- a_star_epsilon
- next_best_assignment

The targets that fail:
- mapf_prioritized_sipp
- cbs
- ecbs
- ecbs_ta
- cbs_ta
- sipp
- default_target (as a consequence of above errors)

I have also attached a file of the entire output for your records. 
[libMultiRobotPlanning_make_output.txt](https://github.com/whoenig/libMultiRobotPlanning/files/5585500/libMultiRobotPlanning_make_output.txt)

**Comment by whoenig** [comment]
Perhaps this helps: https://github.com/PX4/PX4-Avoidance/issues/173. Looks like you might have multiple yaml-cpp installed and would need to remove one of them.

**Comment by JustinKottinger** [comment]
Closing issue since this seems to be an issue with my machine and not the library.
