### ISSUE TITLE
Paper question

### ISSUE THREAD

**Issue by Iko-Git** [whoenig/libMultiRobotPlanning#25]
Thanks for this interesting developed search algorithms library. 
I'd like to kindly ask if there's a paper that describes the developed ECBS, and the difference with the CBS. Also, if a summary about the difference between ECBS and CBS can be provided that would be highly appreciated

**Comment by whoenig** [comment]
You can find the academic references in the source code. For ECBS it is here: https://github.com/whoenig/libMultiRobotPlanning/blob/master/include/libMultiRobotPlanning/ecbs.hpp#L30-L34. I hope that helps!
