### ISSUE TITLE
Error while running the test and the example available in the README

### ISSUE THREAD

**Issue by Iko-Git** [whoenig/libMultiRobotPlanning#26]
Thanks for the script provided. Kindly, I have two questions about errors I am facing while running the provided examples in the README.

1. After running `python3 ../test/test_next_best_assignment.py TestNextBestAssignment.test_1by2` I am facing the following output
```
E
======================================================================
ERROR: test_1by2 (__main__.TestNextBestAssignment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../test/test_next_best_assignment.py", line 28, in test_1by2
    r = self.runNextBestAssignment(mapping)
  File "../test/test_next_best_assignment.py", line 15, in runNextBestAssignment
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './next_best_assignment': './next_best_assignment'

----------------------------------------------------------------------
Ran 1 test in 0.010s

FAILED (errors=1)

```
2. After running `python3 ../example/visualize.py ../benchmark/32x32_obst204/map_32by32_obst204_agents10_ex1.yaml output.yaml` I am facing the following output
```
../example/visualize.py:163: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  map = yaml.load(map_file)
Traceback (most recent call last):
  File "../example/visualize.py", line 165, in <module>
    with open(args.schedule) as states_file:
FileNotFoundError: [Errno 2] No such file or directory: 'output.yaml'
```
Any recommendations to overcome these errors is highly appreciated

**Comment by whoenig** [comment]
1. It seems like your build wasn't successful? Make sure that you have the binary `build/next_best_assignment` in your folder, after running `cmake` and `make`.
2. You can only visualize a result after you created one, which requires the binary files to work, and to be executed (see 1.)

**Comment by Iko-Git** [comment]
It has been built and tested correctly after installing all the dependencies. Thanks

**Comment by Iko-Git** [comment]
I'd like to kindly ask further two questions. Please let me know if I have to post the questions in a single issue. 
How can I see each agent's path knots in the visualization? 
Also, how can I save see the final path x, y values for each agent (e.g. in an external .xlsx file)?
I do appreciate your support
