### ISSUE TITLE
Low-level search in CBS-TA

### ISSUE THREAD

**Issue by aakash0641** [whoenig/libMultiRobotPlanning#38]
Hi,
After reading the paper for CBS-TA, I had the understanding that CBS-TA uses A* search for low-level search (while resolving conflicts) (i.e. during execution of CBS part). But on going through the code, it seems that CBS-TA uses Dijkstra's algorithm for both the 1st assignment, and all subsequent assignments. Please let me know if I am missing something. I had started a thread on the discussion section, but it seemed that it was not sending notifications, so used this forum.

**Comment by aakash0641** [comment]
An update: I realised my fault. I found that the conflict resolution by means of CBS used A*. But the root nodes (of firstAssignment and all subsequent nextBestAssignments) used Dijkstra. Am I right now ?

**Comment by whoenig** [comment]
Closing this in favor of https://github.com/whoenig/libMultiRobotPlanning/discussions/37.
