### ISSUE TITLE
Built for Crazyflie? :D

### ISSUE THREAD

**Issue by NicksonYap** [whoenig/libMultiRobotPlanning#9]
Hi  @whoenig 

I've been working on Crazyflies for quite a while, digging for reference code for Crazyflie and realised you have a lot of other useful repos for such as this repo (libMultiRobotPlanning ) and uav_trajectories

Are they some how built for Crazyflies in mind?

Regards
Nickson

**Comment by whoenig** [comment]
Hi Nickson,
Uav_trajectories can generate trajectories for a single Crazyflie. I used
it to generate the example figure8 in the crazyswarm.

Libmultirobotplanning could be used to generate collision-free timed way
points that can be executed on CFs. However, there are still some parts
missing to generate collision-free trajectories. You can find my papers on
that topic at act.usc.edu. I hope to add the missing code to my open source
repositories soon.
